### ISSUE TITLE
Would be nice to be able to get the content via the file path

### ISSUE THREAD

**Issue by Thairam** [estruyf/vsts-file-creator#25]
Assuming that in my project I have the following file in the "_../config/base.json_" directory:
```
{
  "baseUrl": "$(baseUrl)",
  "user": "$(defaultUser)",
  ...
}
```
It would be nice to be able to get the file in the task instead of providing the content directly.

Something similar to:

```yml
- task: file-creator@6
  inputs:
    filepath: "$(System.DefaultWorkingDirectory)/config/config.json"
    filecontent: |
      cat $(System.DefaultWorkingDirectory)/config/base.json
    fileoverwrite: true
    verbose: true
  displayName: "Cria o arquivo de configurações config.json"
```
